# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d37f2f3bcc04755b71252185d36c1fb1f174fa2329c931593b08db75b34f5ae3551249a2a2140332c33d3555ae7e52d84a008062cbc1a7eaf13d365822765f

test:
  secret_key_base: feb5a7fac2ea79a60cbe16833fbee43055c2728d3efcf822645cd25eedabada1a3e022f80721bdcad0c6471b4e0123bc3f690b20ef1d6ce7cf17624a2fbadc46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
